[package]
name = "rust-model-checker"
version = "0.1.0"
authors = ["bene"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.17.0"
regex = "0.2.0"

[build-dependencies]
lalrpop = "0.17.0"
